# Generated by Django 3.2 on 2022-01-10 07:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='contents',
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=tinymce.models.HTMLField(default='SOME STRING'),
        ),
    ]
