# Generated by Django 3.2 on 2022-02-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_category_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
