# Generated by Django 3.2 on 2022-01-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
