# Generated by Django 3.2 on 2022-01-27 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20220127_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
