# Generated by Django 3.2 on 2022-02-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='file',
            field=models.FileField(null=True, upload_to='files/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
