# Generated by Django 3.2 on 2022-02-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20220214_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
