# Generated by Django 4.1.3 on 2022-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0013_auto_20220214_1110"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="desc",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="articles",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
