# Generated by Django 4.1.3 on 2022-11-08 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0015_alter_articles_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["updated"]},
        ),
    ]
