# Generated by Django 4.1.3 on 2022-11-23 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0016_alter_comment_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articles",
            name="content",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="file",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="hashtags",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="title",
        ),
        migrations.RemoveField(
            model_name="articles",
            name="url",
        ),
        migrations.AddField(
            model_name="articles",
            name="BookName",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="ID",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="VerseID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="Volume",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="bookID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="chapterID",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articles",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True,null=True, max_length=10),
                default=["no"],
                size=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="articles",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
