# Generated by Django 4.1.3 on 2022-11-23 07:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "articles",
            "0017_remove_articles_content_remove_articles_date_created_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="articles",
            old_name="ID",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="articles",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=10), size=8
            ),
        ),
    ]
