# Generated by Django 4.1.3 on 2022-11-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0018_rename_id_articles_title_alter_articles_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.BigIntegerField()),
                ("name", models.CharField(max_length=500)),
                ("frequency", models.BigIntegerField()),
            ],
        ),
    ]
