# Generated by Django 4.1.3 on 2022-12-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("zh-hans", "简体中文"), ("ko", "한국어")],
                default="en",
                max_length=10,
            ),
        ),
    ]
